### ISSUE TITLE
Convert a todo to a task.

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#186]
- [ ] Extract information from todo
- [ ] Set up task and steps (as instructions by default)
- [ ] Save the todo as a new task including steps.
- [ ] Remove the todo with status TODO_CONVERTED & TODO_DONE

**Comment by dan-solli** [comment]
Tasks are something different. There might be a time and place where new todos actually suggest that a conversion might be a good idea. However, todos are so fundamentally different, the time saved seem abysmal. 
Putting this one in the icebox until further notice.
