### ISSUE TITLE
Build a task from steps and other tasks. 

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#188]
I see how this may include a draggable treeview (or accordion if failed)
Also drag and drop to rearrange, as well as new Task and new Step. 

- [x] Make sure the task and different types of steps have been modeled in advance (UML)
~- [ ] Make optional fields optional for real, use a button group.~
- [x] Figure out strategy to save steps in the right way.
- [x] Introduce the possibility to toggle edit and save.
- [x] Introduce the possibility to reorder steps - and save the change.
- [x] Look over how file uploads work. Right now, it's in a state of flux.
~ - Might actually need to take a look at the single components for file uploads and selection of documents.~
- [x] Split this issue into separate issues. This one feels too big at the moment.
