### ISSUE TITLE
Saving/updating changes to tasks and underlying steps. 

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#260]
- [x] New/Save task => Vuex -> POST task
- [x] New step => Add to task's step-list => Vuex (Store)
- [x] Change step order => PATCH task/order (send list of uuid) 
- [x] Delete task => Vuex -> DELETE task
- [x] Delete step => DELETE step => Change step order

Components dispatch every tiny change to Vuex, holding a dirty-flag somehow.

**Comment by dan-solli** [comment]
This is now a placeholder for other issues. Checkboxes mean the issue has been created.

**Comment by dan-solli** [comment]
All what this is has been given their own issues.
