### ISSUE TITLE
Creation of Group

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#31]
A group can be a family. Or just a group of caretakers around a person.

- [x] Create the concept of a Group a User can belong to.
- [x] The relationship a User has to a Group has to be specified. (Member, Admin, Voyeur etc)
- [ ] Figure out how a User can be invited or join a Group

**Comment by dan-solli** [comment]
Roles:
Admin: inga begränsningar
Family: Jämställd med användaren, kan däremot inte planera andras planer.
Ombud: Får planera andras uppgifter. Men alla planermåste godkännas av användaren.
(Användaren kan lämna fullmakt)
Stödperson: Read-only
