### ISSUE TITLE
[Domain Class] Group/Family

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#51]
## Database
- [x] ER-analysis - add to diagram, properties and all.
- [x] Figure out Neo4J-realization (ie labels, et al)
- - [x] Label on node
- - [x] Label on relationships
- [ ] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Route
- [x] Make sure route is accessible and hooked up.

### Vuex
- [x] Create new module
- [x] I18n if necessary

### Router
- [x] Add to router.

### Repository
- [x] Create the actual domain class specific repository.
- [x] Add to repository factory

#### Create
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Collection
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Single Item
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Update
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Delete
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu
