### ISSUE TITLE
[Domain Class] Location

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#76]
## Purpose and concern

A location is a geolocation point on earth. 
- It holds Rooms
- It has a Weather

## Database
- [x] ER-analysis - add to diagram, properties and all.
- [x] Figure out Neo4J-realization (ie labels, et al)
- - [x] Label on node
- - [x] Label on relationships
- [x] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Route
- [X] Make sure route is accessible and hooked up.

### Tests
- [X]

**Comment by dan-solli** [comment]
## For debounce/throttle

[https://stackoverflow.com/questions/56821337/vuetify-throttle-debounce-v-autocomplete](https://stackoverflow.com/questions/56821337/vuetify-throttle-debounce-v-autocomplete)
