### ISSUE TITLE
[Domain Class] Room

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#77]
## Purpose and concerns

- A _Room_ exist at a _Location_
- A _Room_ has _Storages_ which can be storage containers or other actionable things. 
- A _Room_ is geographically located at its location. 

## Database
- [ ] ER-analysis - add to diagram, properties and all.
- [ ] Figure out Neo4J-realization (ie labels, et al)
- - [ ] Label on node
- - [ ] Label on relationships
- [ ] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Route
- [ ] Make sure route is accessible and hooked up.
