### ISSUE TITLE
[Domain Class] Storage

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#78]
## Purpose and concerns

- A _Storage_ is the container of something.
- A _Storage_ is located in a _Room_
- A _Storage_ may have _Actions_ bound to it. (If the _Storage_ is a trashcan, it may have the _Action_ **Empty**)
- A _Storage_ can show _Tasks_ involving it. 
- A _Storage_ can itself contain other _Storage_ recursively. Example: A cleaning closet can contain several different containers/areas with different tools. 
- A _Storage_ can contain _Equipment_ which may be used for certain _Tasks_. 

## Database
- [ ] ER-analysis - add to diagram, properties and all.
- [ ] Figure out Neo4J-realization (ie labels, et al)
- - [ ] Label on node
- - [ ] Label on relationships
- [ ] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Route
- [ ] Make sure route is accessible and hooked up.
