### ISSUE TITLE
[Domain Class] Equipment

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#79]
## Purpose and concerns

- A _Equipment_ is a kind of tool.
- A _Equipment_ is located in a _Storage_
- A _Equipment_ **may** be located in a _Room_, but that need some real world cases to clarify if necessary.
- A _Equipment_ may have _Actions_ Example: Washing machine.
- A _Equipment_ may have different sets of variables tied to it. Example: A washing machine has several different programs. The washing machine itself is the same. These sets of variables indicate how the machine should be set up to run. **This may be a separate issue/DC**
- A _Equipment_ may also be consumable. **This may be a different class like _InventoryItem_**

## Database
- [ ] ER-analysis - add to diagram, properties and all.
- [x] Figure out Neo4J-realization (ie labels, et al)
- - [x] Label on node
- - [ ] Label on relationships
- [ ] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Route
- [x] Make sure route is accessible and hooked up.

### Vuex
- [x] Create new module
- [x] I18n if necessary

### Router
- [x] Add to router.

### Repository
- [x] Create the actual domain class specific repository.
- [x] Add to repository factory

#### Create
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Collection
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Single Item
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Update
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Delete
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu
