### ISSUE TITLE
[Implement Domain Class: Client] Location

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#86]
### Vuex
- [x] Create new module
- [x] I18n if necessary

### Router
- [x] Add to router.

### Repository
- [x] Create the actual domain class specific repository.
- [x] Add to repository factory

#### Create
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Collection
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Single Item
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Update
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Delete
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu
