### ISSUE TITLE
[Implement Domain Class: Client] Storage

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#88]
### Vuex
- [ ] Create new module
- [ ] I18n if necessary

### Router
- [ ] Add to router.

### Repository
- [ ] Create the actual domain class specific repository.
- [ ] Add to repository factory

#### Create
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Collection
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Read: Single Item
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Update
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu

#### Delete
- [ ] I18n
- [ ] Tour
- [ ] Tooltips
- [ ] Hotkeys
- [ ] Right click context menu
