### ISSUE TITLE
Construct a file-browser

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#97]
It should be generic:

- It needs to have a restricted mode, where you can only pick from existing documents. This one should 
probably be displayed as a multiselect modal, picking from a grid. It needs to support live filtering based on filename and sorting on name, size and recently uploaded/changed. This is basically an attachment picker. MAYBE this could be a component as a partial view to enable drag and drop between the file browser and the entity that needs to be modified.
- It needs a non-restricted mode, where you can upload, rename, delete och touch/crop/resize. This is the pure file browser manager. 
- It should contain some sort of file upload component which collects the actual file object, but also the opportunity to edit file data and possible downsize/crop. This should probably also be best fit as a modal. And this component should probably be generic and its own component.
~ - Knowing myself, it needs to support folders as well. Argh.~

This is a prerequisite to the  Domain Class "Document"

- [ ] A general file browser where you can find all your documents and:
  - Upload new
  - Edit/crop/resize/whatever already uploaded documents.
  - Search for files based on original filename (should be possible to search for tags as well)
  - Delete uploaded files
- [x] A document picker, which has none of the upload/edit/delete capabilities. 
  - Hmmm, maybe upload. I gotta "feel" what seems to be appropriate here.
  - This component has to be reusable.
- [x] An upload modal/dialog with single and carousel preview.
  - The component has to be reusable because it will be EVERYWHERE
- [x] In the distant future it needs to support folders to ease organisation. I dread it, I do.

From Issue#75

I dread this, but it has to be done. 

Creation of a OttraFileUpload component. It will be necessary shortly. Things to consider:

- [x] How to store stuff on the server side.
- [x] How to keep track of stuff in the database.
- [ ] How to restrict stuff for fetching in the database.
- [x] Return urls to uploaded content or package the stuff immediately?
- [ ] While uploading, pre-crop, pre-resize or waste all the space?
- [ ] Image quality may be REALLY important to users, which has to be considered. Maybe set an upload limit size and thus delegating the responsibility of reducing image quality to the user?

**Comment by dan-solli** [comment]
Right click context menu: [https://codepen.io/anon/pen/QPoYOQ?editors=1010#anon-login](https://codepen.io/anon/pen/QPoYOQ?editors=1010#anon-login)
Treeview (for folders): [https://vuetifyjs.com/en/components/treeview#slots](https://vuetifyjs.com/en/components/treeview#slots)

**Comment by dan-solli** [comment]
Folders be damned. Users get a flat structure until I learn how to do stuff (or appropriate support is added to Vuetify)

**Comment by dan-solli** [comment]
This is now being blocked by other stuff. There is no place where it can be tested. I can choose between the proper stuff, or allow a logged in user to set his avatar. And I think an Avatar it will be.

Also the whole issue should be split into subissues.

**Comment by dan-solli** [comment]
Issue split into subissues.
