### ISSUE TITLE
[Implement Domain Class: Server] Document

### ISSUE THREAD

**Issue by dan-solli** [dan-solli/ottra#99]
## Database
- [ ] ER-analysis - add to diagram, properties and all.
- [ ] Figure out Neo4J-realization (ie labels, et al)
- - [ ] Label on node
- - [ ] Label on relationships
- [ ] Write a PoC data block for import (ie test/mock-data)

### Model
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary

### Service
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Write tests for functionality outside main call chain.

### Controller
- [ ] Figure out what functionality will be needed beside CRUD and implement
- [ ] Implement CRUD
- [ ] I18n if necessary
- [ ] Validation per route

### Route
- [ ] Make sure routes are accessible and hooked up.

**Comment by dan-solli** [comment]
Done
